name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: |
          mkdir -p output
          cp index.html output/
          cd output
          zip -r ../Clumsy.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: Clumsy
          path: Clumsy.zip
